{
  "status": "SUCCESS",
  "cpu_usage": [
    "25"
  ],
  "stdout": [
    "execpath\n",
    "ncap_remote/ncap_utils SCRIPTPATH\n",
    "ncap_remote/run_epi.sh\n",
    "epi-ncap/cunninghamlabEPI/results/jobepi_demo/logs/DATASET_NAME:dataset3.json_STATUS.txt\n",
    "Completed 242 Bytes/242 Bytes (6.1 KiB/s) with 1 file(s) remaining\rdownload: s3://epi-ncap/cunninghamlabEPI/results/jobepi_demo/logs/DATASET_NAME:dataset3.json_STATUS.txt to ncap_remote/ncap_utils/statusdict.json\n",
    "Completed 258 Bytes/258 Bytes (679 Bytes/s) with 1 file(s) remaining\rupload: ncap_remote/ncap_utils/statusdict.json to s3://epi-ncap/cunninghamlabEPI/results/jobepi_demo/logs/DATASET_NAME:dataset3.json_STATUS.txt\n",
    "2633, is the pid of the background process\n",
    "execpath\n",
    "/home/ubuntu/ncap_remote/run_epi_internal.sh\n",
    "3\n"
  ],
  "instance": "i-0d8234d272a5f5a26",
  "reason": [
    "aws s3 sync ./ \"s3://$bucketname/$groupdir/$resultdir/per_hp\""
  ],
  "command": "44d51c38-734e-4c7d-aba9-ae206e83293b",
  "stderr": [
    "2020-02-23 05:32:51.827286: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory\n",
    "2020-02-23 05:32:51.827956: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory\n",
    "2020-02-23 05:32:51.827980: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n",
    "2020-02-23 05:33:34.780261: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1\n",
    "2020-02-23 05:33:35.251239: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n",
    "2020-02-23 05:33:35.251280: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-172-31-67-245): /proc/driver/nvidia/version does not exist\n",
    "2020-02-23 05:33:35.251731: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA\n",
    "2020-02-23 05:33:35.357966: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499995000 Hz\n",
    "2020-02-23 05:33:35.358650: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55e3b7e2e7a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:\n",
    "2020-02-23 05:33:35.358682: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version\n",
    "WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/epi/lib/python3.6/site-packages/tensorflow_probability/python/bijectors/masked_autoregressive.py:310: AffineScalar.__init__ (from tensorflow_probability.python.bijectors.affine_scalar) is deprecated and will be removed after 2020-01-01.\n",
    "Instructions for updating:\n",
    "`AffineScalar` bijector is deprecated; please use `tfb.Shift(loc)(tfb.Scale(...))` instead.\n"
  ],
  "input": "cunninghamlabEPI/inputs/epidata/dataset3.json"
}
